### ISSUE TITLE
Does not work after heroku open

### ISSUE THREAD

**Issue by AliceSum** [mars/heroku-nextjs#26]
I don't see my app and only see this after doing all those Quick Start step.

Heroku | Welcome to your new app!
Refer to the documentation if you need help deploying.

**Comment by mars** [comment]
How did you deploy it? There is no **Quick Start** for this repo… See [Production Deployment](https://github.com/mars/heroku-nextjs/blob/master/README.md#user-content-production-deployment) for the steps to deploy.

When you see **Heroku | Welcome to your new app!** displayed, that indicates that nothing has been deployed, yet.

**Comment by AliceSum** [comment]
I see  Next app working locally in the link you showed. Do I have to use Next.js with it ?

I just deployed my app with github way rather than this way, and it works!
