### ISSUE TITLE
Could you make it work for nextjs-express example?

### ISSUE THREAD

**Issue by rajaraodv** [mars/heroku-nextjs#4]
I am trying to get [next.js+express app from next.js examples](https://github.com/zeit/next.js/tree/master/examples/custom-server-express)working on heroku but it doesn't. I keep getting `module 'next' not found`. Wondering what I need to change to make it work.

**Comment by mars** [comment]
Curious question indeed! I was able to make it work by copying the custom server example out to it's own repo, then following those [Production Deployment](https://github.com/mars/heroku-nextjs#production-deployment) steps on the README.

Here's that example revised for Heroku:
https://github.com/mars/heroku-nextjs-custom-server-express

…and a sample deployment:
https://nextjs-custom-server-express.herokuapp.com

**Comment by mars** [comment]
I hope that new example is useful. Let me know how it goes 😄
