### ISSUE TITLE
How to deploy to heroku nextjs

### ISSUE THREAD

**Issue by ShintaroNippon** [mars/heroku-nextjs#49]
I'm using this code in package.json

> 
"scripts": { 
"build": "cd app && next build",
 "start": "npm run build && env NODE_ENV=production node app.js",
 "dev": "nodemon --ignore app/ app.js" },

And i wanna deploy to heroku app...

I have tried too

> 
"start": "next start -p $PORT",

I'm using this boilerplate: https://github.com/MustansirZia/next-express-bootstrap-boilerplate

Thanks in advance

**Comment by mars** [comment]
Hi @ShintaroNippon,

You can follow the [Production Deployment](https://github.com/mars/heroku-nextjs/blob/master/README.md#user-content-production-deployment) directions to deploy an existing Next app.

**Comment by ShintaroNippon** [comment]
I thanks by the reply...
I already tried... that approach.
I'm using a custom app.js as server.js

thanks, Carlos Vieira
