### ISSUE TITLE
Problem installing heroku-nextjs-build from npm

### ISSUE THREAD

**Issue by pfortes** [mars/heroku-nextjs#5]
i get the error:
 **Invalid name: "@mars/heroku-nextjs-build"**

when trying to install with the sugested command : **npm install @mars/heroku-nextjs-build --save**

am i missing something or is there a problem with the repo?

**Comment by mars** [comment]
[StackOverflow answer](http://stackoverflow.com/a/40737983/1432681):

You are trying to install a module that makes use of a `scoped package`. You can spot a `scoped package` by the `@` in the package name.

`Scoped packages` require a npm version greater than `2.7.0`.

You can check your npm version with `npm -v`.

You can update npm by using the command `npm install -g npm`.

For more on `scoped packages`: 

 - https://docs.npmjs.com/getting-started/scoped-packages
 - https://docs.npmjs.com/misc/scope

**Comment by pfortes** [comment]
I had npm v 3.10.8, updating to 4.0.5 did the trick, thank you.
