### ISSUE TITLE
App not compatible with buildpack

### ISSUE THREAD

**Issue by tkao-cursive** [mars/heroku-nextjs#56]
I'm getting this error when trying to deploy code:

`remote: -----> App not compatible with buildpack: https://github.com/mars/heroku-nextjs.git
remote:        bash: /tmp/codon/tmp/buildpacks/cc998aa50faebde1ea66717737aec22c884e4936/bin/detect: No such file or directory
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed`

How can I get around this?

**Comment by mars** [comment]
The Javascript app, specifically its `package.json`, must be at the root of the git repo, not in a sub-directory.

**Comment by jucemar** [comment]
I am with the same problem. My package.json is in the root of the project.

**Comment by jucemar-dimon** [comment]
> The Javascript app, specifically its `package.json`, must be at the root of the git repo, not in a sub-directory.

I am with the same problem. My package.json is in the root of the project.

**Comment by mars** [comment]
`package.json` missing from the root is the only thing that causes this error for the Node buildpack, used by default for this Next.js javascript app.

Is `package.json` committed to the git repo? Are you deploying the correct git branch to Heroku?

Is your app using additional or different buildpacks? Maybe it's an error from a different buildpack which would have different compatibility requirements. `heroku buildpacks` command will list them for an app.

**Comment by TrueshotBarrage** [comment]
Not to beat a dead horse per se, but I also reproduce the error as the commenters above. My `package.json` is in the root, of course, and deployment succeeds with the default Nodejs buildpack on Heroku, but fails with the above error with this one. Any ideas?

**Comment by hannupekka** [comment]
Same here with `create-next-app`. `package.json` is in the root.
