### ISSUE TITLE
App not compatible with buildpack error (but I may know why)

### ISSUE THREAD

**Issue by connor-odoherty** [mars/heroku-nextjs#58]
Hey there, I have just started a new Next JS app using create-next-js-app. When I deploy it to my Heroku environment using this buildpack, I run into the error (as mentioned in issue 56):

```
-----> Building on the Heroku-20 stack
-----> Using buildpack: https://github.com/mars/heroku-nextjs.git
-----> App not compatible with buildpack: https://github.com/mars/heroku-nextjs.git
       bash: /tmp/codon/tmp/buildpacks/cc998aa50faebde1ea66717737aec22c884e4936/bin/detect: No such file or directory
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed
 ```

As you can see below, I have my package.json committed at the root, BUT I use the `/src` directory to contain my Next JS pages and such. This seems like a fairly common pattern. Is it possible that using the `/src` pattern instead of putting the pages directory up at the root level is causing issues with the buildpack?

![image](https://user-images.githubusercontent.com/10620559/128926147-63054b9e-e511-438e-8832-3f48b823cad5.png)

**Comment by connor-odoherty** [comment]
Update: I tried deploying with a fresh create-nextjs-app, without the src pattern, and am still running into the issue

Does using `heroku buildpacks:set https://github.com/mars/heroku-nextjs.git` not set the correct buildpack?

**Comment by mars** [comment]
This is not a buildpack, it's an example repo. So, setting it as a buildpack will not work.

You don't need a special buildpack for Next apps. Just use the Node buildpack (which will auto-detect if no buildpacks are explicitly set), and Next will build & run fine.

**Comment by sloreti** [comment]
This is understandably pretty confusing since it's listed as a buildpack on [Heroku's site](https://elements.heroku.com/buildpacks/mars/heroku-nextjs) (see bottom of page).

**Comment by mars** [comment]
That is so weird @sloreti. This app has never been a buildpack, never contained `bin/detect`, `bin/compile`, or `bin/release`  to work as a buildpack. I wonder if people mistakenly setting it as buildpack, attempting app deploys, has lead Heroku Elements to believe it is a buildpack 🙈
