### ISSUE TITLE
App is not compatible with buildpack

### ISSUE THREAD

**Issue by Wizardzaron** [mars/heroku-nextjs#63]
Hi some I'm realtively new to using buildpacks that aren't made by heroku and I was wondering if someone could help. For the past several hours I've been trying to put my next.js website onto heroku using the nodejs and mars-next.js buildpack but I keep getting this error everytime I deploy the branch.

App not compatible with buildpack: https://github.com/mars/heroku-nextjs.git
       bash: line 1: /tmp/codon/tmp/buildpacks/cc998aa50faebde1ea66717737aec22c884e4936/bin/detect: No such file or directory

I have tried watching youtube videos, google, and chatgpt but I can't get a solution to this problem. I hope I don't need to restart my project from scratch or something.  If someone could help I would appreciate it

P.S. I did change npm start to this,     "start": "next start -p $PORT",

**Comment by mars** [comment]
@Wizardzaron this heroku-nextjs repo is not a buildpack. That's why it doesn't work.

Following the instructions on the README, there's no need to specify a buildpack, because Heroku will auto-detect that your Next.js app needs Node.js, automatically will use Heroku's Node buildpack.
